[package]
name = "anon_survey"
version = "0.1.0"
authors = ["Jacob White <white570@purdue.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
